<?php

use Phinx\Migration\AbstractMigration;

class UpdateYeastDescription extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     *
     * Uncomment this method if you would like to use it.
     *
    public function change()
    {
    }
    */

    /**
     * Migrate Up.
     */
    public function up()
    {
      $table = $this->table('yeasts');
      $this->execute("ALTER TABLE `yeasts` CHANGE COLUMN `description` `description` varchar(1023) NOT NULL;");
      $this->execute("UPDATE yeasts SET `description`='This yeast is famous for its clean flavors, balance and ability to be used in almost any style ale. It accentuates the hop flavors and is extremely versatile.' WHERE `id` = 1;
        UPDATE yeasts SET `description`='A classic ESB strain from one of England\'s largest independent breweries. This yeast is best suited for English style ales including milds, bitters, porters, and English style stouts. This yeast will leave a beer very clear, and will leave some residual sweetness.' WHERE `id` = 2;
        UPDATE yeasts SET `description`='This is the yeast from one of the oldest stout producing breweries in the world. It produces a slight hint of diacetyl, balanced by a light fruitiness and slight dry crispness. Great for Irish ales, stouts, porters, browns, reds and a very interesting pale ale.' WHERE `id` = 3;
        UPDATE yeasts SET `description`='This yeast is a little more attenuative than WLP002. Like most English strains, this yeast produces malty beers. Excellent for all English style ales including bitter, pale ale, porter, and brown ale.' WHERE `id` = 4;
        UPDATE yeasts SET `description`='Ferments dry and flocculates very well. Produces a distinctive ester profile. Good choice for most English style ales including bitter, pale ale, porter, and brown ale.' WHERE `id` = 5;
        UPDATE yeasts SET `description`='Clean, highly flocculent, and highly attenuative yeast. This yeast is similar to WLP002 in flavor profile, but is 10% more attenuative. This eliminates the residual sweetness, and makes the yeast well suited for high gravity ales. It is also reaches terminal gravity quickly. 80% attenuation will be reached even with 10% ABV beers.' WHERE `id` = 6;
        UPDATE yeasts SET `description`='Our \"Brewer Patriot\" strain can be used to reproduce many of the American versions of classic beer styles. Similar neutral character of WLP001, but less attenuation, less accentuation of hop bitterness, slightly less flocculation, and a little tartness. Very clean and low esters. Great yeast for golden, blonde, honey, pales and German alt style ales.' WHERE `id` = 7;
        UPDATE yeasts SET `description`='Produces a clean, malty beer. Pleasant ester character, can be described as \"bready.\" Can ferment successfully, and clean, at higher temperatures. This yeast combines good flocculation with good attenuation.' WHERE `id` = 8;
        UPDATE yeasts SET `description`='Malty, Northern European-origin ale yeast. Low ester production, giving a clean profile. Little to no sulfur production. Low attenuation helps to contribute to the malty character. Good for Alt, Kolsch, malty English ales, and fruit beers.' WHERE `id` = 9;
        UPDATE yeasts SET `description`='Dry, malty ale yeast. Provides a complex, oakey ester character to your beer. Hop bitterness comes through well. This yeast is well suited for classic British pale ales, bitters, and stouts. Does not flocculate as much as WLP002 and WLP005.' WHERE `id` = 10;
        UPDATE yeasts SET `description`='Traditional mixed yeast culture. British style character, slightly fruity, with a hint of sulfur production. This yeast can be used for many different beer styles. The most traditional choices would be English style ales including milds, bitters, porters, and English style stouts. North American style ales will also benefit from fermentation with WLP017. The beer will clear easily.' WHERE `id` = 11;
        UPDATE yeasts SET `description`='Flavorful British style yeast. Drier finish than many British ale yeast. Produces slightly fruity and bready character. Good top fermenting yeast strain, is well suited for top cropping (collecting). This yeast is well suited for classic British milds, pale ales, bitters, and stouts. Does not flocculate as much as WLP002 and WLP005.' WHERE `id` = 12;
        UPDATE yeasts SET `description`='From the famous brewing town of Burton upon Trent, England, this yeast is packed with character. It provides delicious subtle fruity flavors like apple, clover honey and pear. Great for all English styles, IPA\'s, bitters, and pales. Excellent in porters and stouts.' WHERE `id` = 13;
        UPDATE yeasts SET `description`='Scotland is famous for its malty, strong ales. This yeast can reproduce complex, flavorful Scottish style ales. This yeast can be an everyday strain, similar to WLP001. Hop character is not muted with this strain, as it is with WLP002.' WHERE `id` = 14;
        UPDATE yeasts SET `description`='From a small brewpub in Cologne, Germany, this yeast works great in Kolsch and Alt style beers. Good for light beers like blond and honey. Accentuates hop flavors, similar to WLP001. The slight sulfur produced during fermentation will disappear with age and leave a super clean, lager like ale.' WHERE `id` = 15;
        UPDATE yeasts SET `description`='Traditional Alt yeast from Dusseldorf, Germany. Produces clean, slightly sweet alt beers. Does not accentuate hop flavor as WLP029 does.' WHERE `id` = 16;
        UPDATE yeasts SET `description`='This yeast produces a beer that is malty, but well-balanced. Expect flavors that are toasty with malt-driven esters. Highly flocculent and good choice for English pale ales, English brown ales, and mild ales.' WHERE `id` = 17;
        UPDATE yeasts SET `description`='Top-fermenting strain that is traditionally good for top-cropping. Moderately flocculent with a clean, dry finish. Low ester profile, producing a highly balanced English-style beer.' WHERE `id` = 18;
        UPDATE yeasts SET `description`='British style ale yeast with a very dry finish. Medium to low fruit and fusel alcohol production. Good top fermenting yeast strain, is well suited for top cropping (collecting). This yeast is well suited for pale ales, ambers, porters, and stouts.' WHERE `id` = 19;
        UPDATE yeasts SET `description`='A popular ale yeast from the Pacific Northwest. The yeast will clear from the beer well, and leave a malty profile. More fruity than WLP002, English Ale Yeast. Good yeast for English style ales including milds, bitters, IPA, porters, and English style stouts.' WHERE `id` = 20;
        UPDATE yeasts SET `description`='A strain that was widely used for Scotch Whisky production from the early 1950s, producing a complex array of ester compounds and fusel oils, as well as some spicy, clove character. Suitable for Scotch Whisky or American-style Whiskey. Used in high-gravity beers.' WHERE `id` = 21;
        UPDATE yeasts SET `description`='Suitable for American-style whiskey and bourbon. This yeast is famous for creating rich, smooth flavors. Clean and dry fermenting yeast. Will tolerate high alcohol concentrations (15%), and ester production is low. Also popular in high-gravity beers.' WHERE `id` = 22;
        UPDATE yeasts SET `description`='From Northern California. This strain is more fruity than WLP001, and slightly more flocculent. Attenuation is lower, resulting in a fuller bodied beer than with WLP001.' WHERE `id` = 23;
        UPDATE yeasts SET `description`='Our most popular yeast strain is WLP001, California Ale Yeast. This blend celebrates the strengths of California- clean, neutral fermentation, versatile usage, and adds two other strains that belong to the same \'clean/neutral\' flavor category. The additional strains create complexity to the finished beer. This blend tastes more lager like than WLP001. Hop flavors and bitterness are accentuated, but not to the extreme of California. Slight sulfur will be produced during fermentation.' WHERE `id` = 24;
        UPDATE yeasts SET `description`='Yeast strain that produces low ester profile and moderate fusel oils. Temperature and alcohol tolerant and suitable for American-style whiskey using barley or corn base. Also used in high-gravity beers.' WHERE `id` = 25;
        UPDATE yeasts SET `description`='From a tradtional distillery in the heart of Bourbon country, this strain produces a carmel, malty character with balanced ester profile. Suitable for Bourbon or other American Whiskey with barley, rye, or corn as the base grain. Used in high-gravity beers.' WHERE `id` = 26;
        UPDATE yeasts SET `description`='Clean strain that complements malt flavor. Low to moderate esters, when fermentation temperature is below 70°F. Moderate plus ester character over 70°F. Low diacetyl production. Good yeast strain for Biere de Garde, blond, amber, brown ales, and specialty beers.' WHERE `id` = 27;
        UPDATE yeasts SET `description`='Yeast from an historic brewery in Northern California, this strain was embraced by the early pioneers of craft beer in America and continues to be a great choice for those seeking to use a traditional British-style yeast. A neutral and versatile strain, it is a great choice for pale ales, porters, and stouts.' WHERE `id` = 28;
        UPDATE yeasts SET `description`='Marked by a clean, fast fermentation, this strain is ideal for any neutral grain spirit. Alcohol and temperature tolerant. Used in high-gravity beers.' WHERE `id` = 29;
        UPDATE yeasts SET `description`='This is a blend of ale and lager yeast strains. The strains work together to create a clean, crisp, light American lager style ale. A pleasing estery aroma may be perceived from the ale yeast contribution. Hop flavors and bitterness are slightly subdued. Slight sulfur will be produced during fermentation, from the lager yeast.' WHERE `id` = 30;
        UPDATE yeasts SET `description`='A blend of British ale yeast strains, designed to add complexity to your ale. Moderate fruitiness and mineral-like, with little to no sulfur. Drier than WLP002 and WLP005, but with similar flocculation properties. Good yeast blend for English Pale Ale, Bitter, Porter, Stout, and India Pale Ale.' WHERE `id` = 31;
        UPDATE yeasts SET `description`='A super clean, super-fast fermenting strain. A low ester-producing strain that results in a balanced, neutral flavor and aroma profile. Alcohol-tolerant and very versatile for a wide variety of styles. Similar to California Ale Yeast WLP001 but it generally ferments faster.' WHERE `id` = 32;
        UPDATE yeasts SET `description`='Can ferment up to 25% alcohol. From England. Produces ester character that increases with increasing gravity. Malt character dominates at lower gravities.' WHERE `id` = 33;
        UPDATE yeasts SET `description`='This famous German yeast is a strain used in the production of traditional, authentic wheat beers. It produces the banana and clove nose traditionally associated with German wheat beers and leaves the desired cloudy look of traditional German wheat beers.' WHERE `id` = 34;
        UPDATE yeasts SET `description`='This yeast is used to produce the Oregon style American Hefeweizen. Unlike WLP300, this yeast produces a very slight amount of the banana and clove notes. It produces some sulfur, but is otherwise a clean fermenting yeast, which does not flocculate well, producing a cloudy beer.' WHERE `id` = 35;
        UPDATE yeasts SET `description`='Former Yeast Lab W51 yeast strain, acquired from Dan McConnell. The description originally used by Yeast Lab still fits: \"This strain produces a classic German-style wheat beer, with moderately high, spicy, phenolic overtones reminiscent of cloves.\"' WHERE `id` = 36;
        UPDATE yeasts SET `description`='Large clove and phenolic aroma and flavor, with minimal banana. Refreshing citrus and apricot notes. Crisp, drinkable hefeweizen. Less flocculent than WLP300, and sulfur production is higher.' WHERE `id` = 37;
        UPDATE yeasts SET `description`='Slightly phenolic and tart, this is the original yeast used to produce Wit in Belgium.' WHERE `id` = 38;
        UPDATE yeasts SET `description`='Less phenolic than WLP400, and more spicy. Will leave a bit more sweetness, and flocculation is higher than WLP400. Use to produce Belgian Wit, spiced Ales, wheat Ales, and specialty Beers.' WHERE `id` = 40;
        UPDATE yeasts SET `description`='From one of the few remaining Trappist breweries remaining in the world, this yeast produces the distinctive fruitiness and plum characteristics. Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.' WHERE `id` = 41;
        UPDATE yeasts SET `description`='A high gravity, Trappist style ale yeast. Produces dry beer with slight acidic finish. More â€˜cleanâ€™ fermentation character than WLP500 or WLP530. Not as spicy as WLP530 or WLP550. Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.' WHERE `id` = 42;
        UPDATE yeasts SET `description`='Clean, almost lager like Belgian type ale yeast. Good for Belgian type pales ales and amber ales, or with blends to combine with other Belgian type yeast strains. Biscuity, ale like aroma present. Hop flavors and bitterness are accentuated. Slight sulfur will be produced during fermentation, which can give the yeast a lager like flavor profile.' WHERE `id` = 43;
        UPDATE yeasts SET `description`='Used to produce Trappist style beers. Similar to WLP500, but is less fruity and more alcohol tolerant (up to 15% ABV). Excellent yeast for high gravity beers, Belgian ales, dubbels and trippels.' WHERE `id` = 44;
        UPDATE yeasts SET `description`='An authentic Trappist style yeast. Use for Belgian style ales, dubbels, tripples, and specialty beers. Fruit character is medium, in between WLP500 (high) and WLP530 (low).' WHERE `id` = 45;
        UPDATE yeasts SET `description`='From the Ardennes region of Belgium, this classic yeast strain produces moderate levels of ester and spicy phenolic character. Typically results in a dry, but balanced finish. This yeast is well suited for Belgian dark strongs, Abbey Ales, and Christmas beers.' WHERE `id` = 46;
        UPDATE yeasts SET `description`='Saisons, Belgian Ales, Belgian Reds, Belgian Browns, and White beers are just a few of the classic Belgian beer styles that can be created with this yeast strain. Phenolic and spicy flavors dominate the profile, with less fruitiness then WLP500.' WHERE `id` = 47;
        UPDATE yeasts SET `description`='Classic Saison yeast from Wallonia. It produces earthy, peppery, and spicy notes. Slightly sweet. With high gravity saisons, brewers may wish to dry the beer with an alternate yeast added after 75% fermentation.' WHERE `id` = 48;
        UPDATE yeasts SET `description`='Saison strain with more fruity ester production than with WLP565. Moderately phenolic, with a clove-like characteristic in finished beer flavor and aroma. Ferments faster than WLP565.' WHERE `id` = 49;
        UPDATE yeasts SET `description`='This blend melds Belgian style ale and saison strains. The strains work in harmony to create complex, fruity aromas and flavors. The blend of yeast strains encourages complete fermentation in a timely manner. Phenolic, spicy, earthy, and clove like flavors are also created.' WHERE `id` = 50;
        UPDATE yeasts SET `description`='From East Flanders, versatile yeast that can produce light Belgian ales to high gravity Belgian beers (12% ABV). A combination of fruitiness and phenolic characteristics dominate the flavor profile. Some sulfur is produced during fermentation, which will dissipate following the end of fermentation.' WHERE `id` = 51;
        UPDATE yeasts SET `description`='A blend of Trappist type yeast (2) and one Belgian ale type yeast. This creates a versatile blend that can be used for Trappist type beer, or a myriad of beers that can be described as \'Belgian type\'.' WHERE `id` = 52;
        UPDATE yeasts SET `description`='Produces beer with a high fruit ester characteristic, as well as some slight tartness. Finishes slightly malty, which balances out the esters. Also produces low levels of clovey phenolics. Great yeast choice for a summer Saison that is light and easy-drinking.' WHERE `id` = 53;
        UPDATE yeasts SET `description`='A blend of a traditional German Weizen yeast and Lactobacillus to create a subtle, tart, drinkable beer. Can take several months to develop tart character. Perfect for traditional Berliner Weisse.' WHERE `id` = 54;
        UPDATE yeasts SET `description`='This Belgian strain, used traditionally for 100% Brettanomyces fermentations, produces a slightly tart beer with delicate characteristics of mango and pineapple. Can also be used to produce effervescence when bottle-conditioning.' WHERE `id` = 55;
        UPDATE yeasts SET `description`='Low intensity Brett character. Originally isolated from strong English stock beer, in the early 20th century. The Brett flavors produced are more subtle than WLP650 and WLP653. More aroma than flavor contribution. Fruity, pineapple like aroma. B. claussenii is closely related to B. anomalus.' WHERE `id` = 56;
        UPDATE yeasts SET `description`='Medium intensity Brett character. Classic strain used in secondary fermentation for Belgian style beers and lambics. One Trappist brewery uses this strain in secondary fermentation and bottling to produce their characteristic flavor.' WHERE `id` = 57;
        UPDATE yeasts SET `description`='High intensity Brett character. Defines the \"Brett character\": Horsey, smoky and spicy flavors. As the name suggests, this strain is found most often in Lambic style beers, which are spontaneously fermented beers. Also found in Flanders and sour brown style beers.' WHERE `id` = 58;
        UPDATE yeasts SET `description`='A unique blend perfect for Belgian style beers. Includes Brettanomyces, Saccharomyces, and the bacterial strains Lactobacillus and Pediococcus.' WHERE `id` = 59;
        UPDATE yeasts SET `description`='Blended culture used to produce the classic beer styles of the West Flanders region of Belgium . A proprietary blend of Saccharomyces yeasts, Brettanomyces, Lactobacillus, and Pediococcus, this culture creates a more complex, dark stone fruit characteristic than WLP 655 Belgian Sour Mix' WHERE `id` = 60;
        UPDATE yeasts SET `description`='Inspired by local American brewers crafting semi-traditional Belgian-style ales. This blend creates a complex flavor profile with a moderate level of sourness. It consists of a traditional farmhouse yeast strain and Brettanomyces. Great yeast for farmhouse ales, Saisons, and other Belgian-inspired beers' WHERE `id` = 61;
        UPDATE yeasts SET `description`='Malolactic Fermentation is the conversion of malic acid to lactic acid by bacteria from the lactic acid bacteria family. Lactic acid is less acidic than malic acid, which in turn decreases acidity and helps to soften and/or round out some of the flavors in wine. These liquid cultures are available in vials to inoculate 6 gallons or 1 liter sizes to inoculate 60 gallons.' WHERE `id` = 62;
        UPDATE yeasts SET `description`='This lactic acid bacteria produces moderate levels of acidity and sour flavors found in lambics, Berliner Weiss, sour brown ale and gueze.' WHERE `id` = 65;
        UPDATE yeasts SET `description`='This yeast develops a film (flor) on the surface of the wine. Creates green almond, granny smith and nougat characteristics found in sherry. Can also be used for Port, Madeira and other sweet styles. For use in secondary fermentation. Slow fermentor.' WHERE `id` = 66;
        UPDATE yeasts SET `description`='For use in rice based fermentations. For sake, use this yeast in conjunction with Koji (to produce fermentable sugar). WLP705 produces full body sake character, and subtle fragrance.' WHERE `id` = 67;
        UPDATE yeasts SET `description`='Isolated from Pinot Noir grapes by White Labs in Davis, CA. This strain produces fruity and complex aromas, and is an ideal choice for hardy red wine varieties, as well as aromatic white wines such as Chardonnay. This strain is reliable for difficult fermentations.' WHERE `id` = 68;
        UPDATE yeasts SET `description`='For use in rice-based fermentations. Traditional strain used in Ginjo-shu production because of the yeastâ€™s development of high fragrance components. Also a fairly strong fermenter, but producing a foamless fermentation.' WHERE `id` = 69;
        UPDATE yeasts SET `description`='Classic yeast, used to produce champagne, cider, dry meads, dry wines, or to fully attenuate barley wines/ strong ales. Neutral.' WHERE `id` = 70;
        UPDATE yeasts SET `description`='Champagne isolate used for complexity in whites. Contributes elegance, especially in barrel fermented Chardonnays.' WHERE `id` = 71;
        UPDATE yeasts SET `description`='A wine yeast strain that is less attenuative than WLP715, leaving some residual sweetness. Slightly fruity and will tolerate alcohol concentrations up to 15%. A good choice for sweet mead and cider, as well as Blush wines, GewÃ¼rztraminer, Sauternes, Riesling.' WHERE `id` = 72;
        UPDATE yeasts SET `description`='German in origin, this yeast has high fruit/ester production. Perfect for Riesling and GewÃ¼rztraminer. Moderate fermentation characteristics and cold tolerant.' WHERE `id` = 73;
        UPDATE yeasts SET `description`='Dry wine yeast. Slight ester production, low sulfur dioxide production. Enhances varietal character. WLP730 is a good choice for all white and blush wines, including Chablis, Chenin Blanc, Semillon, and Sauvignon Blanc. Fermentation speed is moderate.' WHERE `id` = 74;
        UPDATE yeasts SET `description`='Classic yeast for white wine fermentation. Slow to moderate fermenter and foam producer. Gives an enhanced creamy texture.' WHERE `id` = 75;
        UPDATE yeasts SET `description`='Neutral, low fusel alcohol production. Will ferment to dryness, alcohol tolerance to 18%. Vigorous fermenter. WLP740 is well suited for Merlot, Shiraz, Pinot Noir, Chardonnay, Cabernet, Sauvignon Blanc, and Semillon.' WHERE `id` = 76;
        UPDATE yeasts SET `description`='German red wine yeast, which results in spicy, fruit aromas. Perfect for Pinot Noir and Zinfandel. Slow to moderate fermenter which is cold tolerant.' WHERE `id` = 77;
        UPDATE yeasts SET `description`='Classic Bordeaux yeast for red wine fermentations. Moderate fermentation characteristics. Tolerates lower fermentation temperatures. Rich, smooth flavor profile.' WHERE `id` = 78;
        UPDATE yeasts SET `description`='High temperature tolerance. Moderate fermentation speed. Excellent for full-bodied red wines, ester production complements flavor. WLP760 is also suitable for Merlot, Chardonnay, Chianti, Chenin Blanc, and Sauvignon Blanc.' WHERE `id` = 79;
        UPDATE yeasts SET `description`='Emphasizes fruit aromas in barrel fermentations. High nutrient requirement to avoid volatile acidity production.' WHERE `id` = 80;
        UPDATE yeasts SET `description`='Classic cider yeast. Ferments dry, but retains flavor from apples. Sulfur is produced during fermentation, but will disappear in first two weeks of aging. Can also be used for wine and high gravity beers.' WHERE `id` = 81;
        UPDATE yeasts SET `description`='Classic pilsner strain from the premier pilsner producer in the Czech Republic. Somewhat dry with a malty finish, this yeast is best suited for European pilsner production.' WHERE `id` = 82;
        UPDATE yeasts SET `description`='Pilsner lager yeast from Southern Czech Republic. Produces dry and crisp lagers, with low diacetyl production.' WHERE `id` = 83;
        UPDATE yeasts SET `description`='This yeast is used to produce the \"California Common\" style beer. A unique lager strain which has the ability to ferment up to 65 degrees while retaining lager characteristics. Can also be fermented down to 50 degrees for production of marzens, pilsners and other style lagers.' WHERE `id` = 84;
        UPDATE yeasts SET `description`='Clean, crisp European lager yeast with low sulfur production. The strain originates from a very old brewery in West Belgium. Great for European style pilsners, dark lagers, Vienna lager, and American style lagers.' WHERE `id` = 85;
        UPDATE yeasts SET `description`='This yeast produces a very malty, bock like style. It does not finish as dry as WLP830. This yeast is much slower in the first generation than WLP830, so we encourage a larger starter to be used the first generation or schedule a longer lagering time.' WHERE `id` = 86;
        UPDATE yeasts SET `description`='This yeast is one of the most widely used lager yeasts in the world. Very malty and clean, great for all German lagers, pilsner, oktoberfest, and marzen.' WHERE `id` = 87;
        UPDATE yeasts SET `description`='From the Alps of southern Bavaria, this yeast produces a beer that is well balanced between malt and hop character. The excellent malt profile makes it well suited for Bocks, Doppelbocks, and Oktoberfest style beers. Very versatile lager yeast, it is so well balanced that it has gained tremendous popularity for use in Classic American style Pilsners. Also good for Helles style lager beer.' WHERE `id` = 88;
        UPDATE yeasts SET `description`='This yeast is characterized by a malty finish and balanced aroma. It is a strong fermentor, produces slight sulfur, and low diacetyl.' WHERE `id` = 89;
        UPDATE yeasts SET `description`='This yeast is used to produce American style lagers. Dry and clean with a very slight apple fruitiness. Sulfur and diacetyl production is minimal.' WHERE `id` = 90;
        UPDATE yeasts SET `description`='This yeast helps to produce a malty, but balanced traditional Munich-style lager. Clean and strong fermenter, it\'s great for a variety of lager styles ranging from Helles to Rauchbier.' WHERE `id` = 91;
        UPDATE yeasts SET `description`='Licensed from Charlie Papazian, this strain can ferment at ale and lager temperatures, allowing brewers to produce diverse beer styles. The recipes in both Papazian\'s books, The Complete Joy of Homebrewing and The Homebrewers Companion, were originally developed and brewed with this yeast.' WHERE `id` = 92;
        UPDATE yeasts SET `description`='Swiss style lager yeast. With proper care, this yeast can be used to produce lager beer over 11% ABV. Sulfur and diacetyl production is minimal. Original culture provided to White Labs by Marc Sedam.' WHERE `id` = 93;
        UPDATE yeasts SET `description`='From Southern Germany, this yeast finishes malty with a slight ester profile. Use in beers such as Oktoberfest, Bock, and Dark Lagers.' WHERE `id` = 94;
        UPDATE yeasts SET `description`='From Mexico City, this yeast produces clean lager beer, with a crisp finish. Good for Mexican style light lagers, as well as dark lagers. This is one of the best lager strains in the White Labs yeast bank; try it with any lager.' WHERE `id` = 95;
        UPDATE yeasts SET `description`='The Budvar strain has a nice malty nose with subtle fruit tones and a rich malt profile on the palate. It finishes malty but dry, well balanced and crisp. Hop character comes through in the finish.' WHERE `id` = 96;
        UPDATE yeasts SET `description`='With a mild fruit and floral aroma this strain has a very dry and clean palate with a full mouthfeel and nice subtle malt character. It has a very clean and neutral finish.' WHERE `id` = 97;
        UPDATE yeasts SET `description`=' The classic American lager strain. This mild, neutral strain produces beers with a nice malty character and a smooth palate. It ferments dry and crisp with minimal sulfur or diacetyl. Beers from this strain exhibit the characteristics of the most popular lager in America.' WHERE `id` = 98;
        UPDATE yeasts SET `description`='A complex and aromatic strain that can be used for a variety of lager beers. This strain is an excellent choice for Classic American Pilsner beers.' WHERE `id` = 99;
        UPDATE yeasts SET `description`='This yeast is a good choice for Dortmund-style lagers. It will ferment crisp and dry with a soft, rounded profile that accentuates hop characteristics.' WHERE `id` = 100;
        UPDATE yeasts SET `description`=' This strain is particularly well suited for producing 19th century-style California Common-style beers. It retains lager characteristics at temperatures up to 65Â°F (18Â°C) and produces malty, brilliantly clear beers. This strain is not recommended for cold temperature fermentation.' WHERE `id` = 101;
        UPDATE yeasts SET `description`='This Carlsberg type yeast is the most widely used lager strain in the world. This strain produces a distinct malty profile with some ester character and a crisp finish. A versatile strain, that is great to use with lagers or Pilsners for fermentations in the 45-55Â°F (8-12Â°C) range. It may also be used for Common beer production with fermentations at 65-68Â°F (18-20Â°C). A thorough diacetyl rest is recommended after fermentation is complete.' WHERE `id` = 102;
        UPDATE yeasts SET `description`='Used by many German breweries to produce rich, full-bodied, malty beers, this strain is a good choice for bocks and doppelbocks. A thorough diacetyl rest is recommended after fermentation is complete.' WHERE `id` = 103;
        UPDATE yeasts SET `description`='Originating from the home of great Pilsners in the Czech Republic, this classic Pilsner strain will finish dry and malty. It is the perfect choice for Bohemian-style Pilsners. Sulfur produced during fermentation can be reduced with warmer fermentation temperatures 58Â°F (14Â°C) and will dissipate with conditioning.' WHERE `id` = 104;
        UPDATE yeasts SET `description`='This is a unique strain, capable of producing fine lagers. It is very smooth, well-rounded and full-bodied. A thorough diacetyl rest is recommended after fermentation is complete.' WHERE `id` = 105;
        UPDATE yeasts SET `description`='This blend of lager strains is designed to produce a rich, malty, complex and full bodied Octoberfest style beer. It attenuates well while leaving plenty of malt character and mouthfeel. This strain is low in sulfur production.' WHERE `id` = 106;
        UPDATE yeasts SET `description`='A true top cropping yeast with low ester formation and a broad temperature range. Fermentation at higher temperatures may produce mild fruitiness. This powdery strain results in yeast that remains in suspension post fermentation. Beers mature rapidly, even when cold fermentation is used. Low or no detectable diacetyl.' WHERE `id` = 111;
        UPDATE yeasts SET `description`='A strong fermenting, true top cropping yeast that produces a dry, slightly tart, crisp beer. Ideal for beers where a low ester profile is desirable.' WHERE `id` = 112;
        UPDATE yeasts SET `description`='A rich mineral profile that is bold and crisp with some fruitiness. Often used for higher gravity ales and when a high level of attenuation is desired.' WHERE `id` = 113;
        UPDATE yeasts SET `description`='Very clean, crisp flavor characteristics with low fruitiness and mild ester production. A very versatile yeast for styles that desire dominant malt and hop character. This strain makes a wonderful â€œhouseâ€ strain. Mild citrus notes develop with cooler 60-66Â°F (15-19ÂºC) fermentations. Normally requires filtration for bright beers.' WHERE `id` = 114;
        UPDATE yeasts SET `description`='This versatile yeast ferments extremely well in dark worts. It is a good choice for most high gravity beers. Beers fermented in the lower temperature range produce a dry, crisp profile with subtle fruitiness. Fruit and complex esters will increase when fermentation temperatures are above 64Â°F (18Â°C).' WHERE `id` = 115;
        UPDATE yeasts SET `description`='This yeast allows malt and hop character to dominate the profile. It ferments dry and crisp, producing well-balanced beers with a clean and neutral finish. Ferments well down to to 64Â°F (18Â°C).' WHERE `id` = 116;
        UPDATE yeasts SET `description`='A mildly malty and slightly fruity fermentation profile. It is less tart and dry than Wyeast 1098 British Ale. With good flocculation characteristics, this yeast clears well without filtration. Low fermentation temperatures will produce a clean finish with a very low ester profile.' WHERE `id` = 117;
        UPDATE yeasts SET `description`='A top cropping yeast strain with unique fermentation and flavor characteristics. Expect distinct fruit esters with a malty, complex profile. Flocculation is high, and the beer will clear well without filtration. A thorough diacetyl rest is recommended after fermentation is complete. This strain can be a slow starter and fermenter.' WHERE `id` = 118;
        UPDATE yeasts SET `description`='With many of the best qualities that brewers look for when brewing American styles of beer, this strainâ€™s performance is consistent and it makes great beer. This versatile strain is a very good choice for a â€œHouseâ€ strain. Expect a soft, clean profile with hints of nut, and a slightly tart finish. Ferment at warmer temperatures to accentuate hop character with an increased fruitiness. Or, ferment cool for a clean, light citrus character. It attenuates well and is reliably flocculent, producing bright beer without filtration.' WHERE `id` = 119;
        UPDATE yeasts SET `description`='This strain produces classic British bitters with a rich, complex flavor profile. The yeast has a light malt character, low fruitiness, low esters and is clean and well balanced.' WHERE `id` = 120;
        UPDATE yeasts SET `description`='Originating from a traditional London brewery, this yeast has a wonderful malt and hop profile. It is a true top cropping strain with a fruity, very light and softly balanced palate. This strain will finish slightly sweet.' WHERE `id` = 121;
        UPDATE yeasts SET `description`='One of the classic ale strains from a Northwest U.S. Brewery. It produces a malty and mildly fruity ale with good depth and complexity.' WHERE `id` = 122;
        UPDATE yeasts SET `description`='A classic British ale profile with good flocculation and malty flavor characteristics. It will finish crisp, clean and fairly dry.' WHERE `id` = 123;
        UPDATE yeasts SET `description`='This terrific all-round yeast can be used for almost any beer style, and is a mainstay of one of our local homebrewers, Mr. Denny Conn. It is unique in that it produces a big mouthfeel and accentuates the malt, caramel, or fruit character of a beer without being sweet or under-attenuated.' WHERE `id` = 124;
        UPDATE yeasts SET `description`='This strain produces ales with a full chewy malt flavor and character, but finishes dry, producing famously balanced beers. Expect moderate nutty and stone-fruit esters. Best used for the production of cask-conditioned bitters, ESB and mild ales. Reliably flocculent, producing bright beer without filtration.' WHERE `id` = 125;
        UPDATE yeasts SET `description`='Our Scottish ale strain is ideally suited for the strong, malty ales of Scotland. This strain is very versatile, and is often used as a â€œhouseâ€ strain as it ferments neutral and clean. Higher fermentation temperatures will result in an increased ester profile.' WHERE `id` = 126;
        UPDATE yeasts SET `description`='A very good cask conditioned ale strain, this extremely flocculent yeast produces distinctly malty beers. Attenuation levels are typically less than most other yeast strains which results in a slightly sweeter finish. Ales produced with this strain tend to be fruity, increasingly so with higher fermentation temperatures of 70-74Â°F (21-23Â°C). A thorough diacetyl rest is recommended after fermentation is complete. Bright beers are easily achieved within days without any filtration.' WHERE `id` = 127;
        UPDATE yeasts SET `description`='This strain is a classic, true top cropping yeast strain from a traditional brewery in Cologne, Germany. Beers will exhibit some of the fruity character of an ale, with a clean lager like profile. It produces low or no detectable levels of diacetyl. This yeast may also be used to produce quick-conditioning pseudo-lager beers and ferments well at cold 55-60Â°F (13-16Â°C) range. This powdery strain results in yeast that remains in suspension post fermentation. It requires filtration or additional settling time to produce bright beers.' WHERE `id` = 128;
        UPDATE yeasts SET `description`='A widely used and alcohol tolerant Abbey yeast that is suitable for a variety of Belgian style ales. This strain produces a nice ester profile as well as slightly spicy alcohol notes. It can be slow to start; however, it attenuates well.' WHERE `id` = 142;
        UPDATE yeasts SET `description`='The classic choice for brewing golden strong ales. This alcohol tolerant strain will produce a complex ester profile balanced nicely with subtle phenolics. Malt flavors and aromas will remain even with a well attenuated dry, tart finish. It may continue to produce CO2 for an extended period after packaging or collection.' WHERE `id` = 143;
        UPDATE yeasts SET `description`='An excellent yeast strain for use in Belgian dark strong ales. This strain has a relatively â€œcleanâ€ profile which allows a rich malt and distinctive ethanol character to shine. Delicate dried fruit esters can be produced when used at higher fermentation temperatures or in a high gravity wort.' WHERE `id` = 144;
        UPDATE yeasts SET `description`='This proprietary blend of a top-fermenting neutral ale strain and a Bavarian wheat strain is a great choice when a subtle German style wheat beer is desired. The complex esters and phenolics from the wheat strain are nicely softened and balanced by the neutral ale strain.' WHERE `id` = 145;
        UPDATE yeasts SET `description`='The classic and most popular German wheat beer strain used worldwide. This yeast strain produces a beautiful and delicate balance of banana esters and clove phenolics. The balance can be manipulated towards ester production through increasing the fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Decreasing the ester level will allow a higher clove character to be perceived. Sulfur is commonly produced, but will dissipate with conditioning. This strain is very powdery and will remain in suspension for an extended amount of time following attenuation. This is true top cropping yeast and requires fermenter headspace of 33%.' WHERE `id` = 146;
        UPDATE yeasts SET `description`='A highly flocculent German wheat beer strain that is the perfect choice for use in Kristallweizen. This yeast strain produces a beautiful and delicate balance of banana esters and clove phenolics similar to the popular Wyeast 3068. However, this strain will sediment rapidly, resulting in bright beer without filtration. The balance can be manipulated towards ester production through increasing fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Sulfur is commonly produced, but will dissipate with conditioning.' WHERE `id` = 147;
        UPDATE yeasts SET `description`='A widely used strain in the production of Witbier and Grand Cru. This yeast will produce spicy phenolics which are balanced nicely by a complex ester profile. The subtle fruit character and dry tart finish will complement wheat malt, orange peel and spice additions typical of Wits.' WHERE `id` = 148;
        UPDATE yeasts SET `description`='One of the great and versatile strains for the production of classic Belgian style ales. This strain produces a beautiful balance of delicate fruit esters and subtle spicy notes, with neither one dominating. Unlike many other Belgian style strains, this strain is highly flocculent and results in bright beers.' WHERE `id` = 149;
        UPDATE yeasts SET `description`='A complex alternative to the standard German wheat strain profile. This strain produces apple, pear, and plum esters in addition to the dominant banana character. The esters are complemented nicely by clove and subtle vanilla phenolics. The balance can be manipulated towards ester production through increasing fermentation temperature, increasing the wort density, and decreasing the pitch rate. Over pitching can result in a near complete loss of banana character. Decreasing the ester level will allow a higher clove character to be perceived. Sulfur is commonly produced, but will dissipate with conditioning. This strain is very powdery and will remain in suspension for an extended amount of time following attenuation. This is true top cropping yeast and requires fermenter headspace of 33%.' WHERE `id` = 150;
        UPDATE yeasts SET `description`='A very versatile strain that produces Saison or farmhouse style beers as well as other Belgian style beers that are highly aromatic, estery, peppery, spicy and citrusy. This strain enhances the use of spices and aroma hops, and is extremely attenuative but leaves an unexpected silky and rich mouthfeel. This strain can also be used to re-start stuck fermentations or in high gravity beers.' WHERE `id` = 151;
        UPDATE yeasts SET `description`='This strain is the classic farmhouse ale yeast. A traditional yeast that is spicy with complex aromatics, including bubble gum. It is very tart and dry on the palate with a mild fruitiness. Expect a crisp, mildly acidic finish that will benefit from elevated fermentation temperatures. This strain is notorious for a rapid and vigorous start to fermentation, only to stick around 1.035 S.G. Fermentation will finish, given time and warm temperatures. Warm fermentation temperatures, at least 90Â°F (32Â°C), or the use of a secondary strain can accelerate attenuation.' WHERE `id` = 152;
        UPDATE yeasts SET `description`='A classic strain for brewing Belgian dubbel or Belgian tripel. This Abbey strain produces a nice balance of complex fruity esters and phenolics, making it desirable for use in other Belgian style ales as well. A flocculent, true top cropping yeast (additional headspace is recommended), that will work over a broad temperature range. This strain makes a great Belgian style â€œhouseâ€ strain.' WHERE `id` = 153;
        UPDATE yeasts SET `description`='Isolated from a small Belgian brewery, this strain produces beers with moderate esters and minimal phenolics. Apple, bubblegum and plum-like aromas blend nicely with malt and hops. This strain will finish dry with a hint of tartness.' WHERE `id` = 154;
        UPDATE yeasts SET `description`='This versatile witbier yeast strain can be used in a variety of Belgian style ales. This strain produces a complex flavor profile dominated by spicy phenolics with low to moderate ester production. It is a great strain choice when you want a delicate clove profile not to be overshadowed by esters. It will ferment fairly dry with a slightly tart finish that compliments the use of oats, malted and unmalted wheat. This strain is a true top cropping yeast requiring full fermenter headspace of 33%.' WHERE `id` = 155;
        UPDATE yeasts SET `description`='English ale yeast selected for its fast fermentation character and its ability to form a compact sediment at the end of fermentation, helping to improve beer clarity. Recommended for the production of a large range of ales and specially adapted to cask-conditioned ones and fermentation in cylindo- conical tanks.' WHERE `id` = 156;
        UPDATE yeasts SET `description`='American ale yeast producing well balanced beers with low diacetyl and a very clean, crisp end palate. Forms a firm foam head and presents a very good ability to stay in suspension during fermentation.' WHERE `id` = 157;
        UPDATE yeasts SET `description`='German ale yeast selected for its ability to form a large firm head when fermenting. Suitable to brew ales with low esters and can be used for Belgian type wheat beers. Its lower attenuation profile gives beers with a good length on the palate.' WHERE `id` = 158;
        UPDATE yeasts SET `description`='Bottom fermenting yeast originating from the VLB - Berlin in Germany recommended for the production of fruity and estery lagers. Its lower attenuation profile gives beers with a good length on the palate.' WHERE `id` = 159;
        UPDATE yeasts SET `description`='This famous yeast strain from Weihenstephan in Germany is used world-wide within the brewing industry. Saflager W-34/70 allows to brew beers with a good balance of floral and fruity aromas and gives clean flavors and high drinkable beers.' WHERE `id` = 160;
        UPDATE yeasts SET `description`='Originating from the Hürlimann brewery in Switzerland. This lager strain’s attenuation profile allows to brew fairly neutral flavor beers with a high drinkability.' WHERE `id` = 161;
        UPDATE yeasts SET `description`='Specialty yeast selected for its estery somewhat peppery and spicy flavor development. Yeast with a good sedimentation: forms no clumps but a powdery haze when resuspended in the beer.' WHERE `id` = 162;
        UPDATE yeasts SET `description`='General purpose ale yeast with neutral flavor profiles. Its low attenuation gives beers with a very good length on the palate. Particularly recom- mended for specialty ales and trappist type beers. Yeast with a good sedimentation: forms no clumps but a powdery haze when resuspended in the beer.' WHERE `id` = 163;
        UPDATE yeasts SET `description`='Specialty yeast selected for wheat beer fermentations. Produces subtle estery and phenol flavor notes typical of wheat beers. Allows to brew beer with a high drinkability profile and presents a very good ability to suspend during fermentation.' WHERE `id` = 164;
        UPDATE yeasts SET `description`='Isolated from a uniquely crafted double IPA out of the Northeastern United States, this yeast produces a balanced fruity ester profile of peaches and light citrus that complements any aggressively hopped beer.' WHERE `id` = 165;
        UPDATE yeasts SET `description`='Isolated from a unique farmhouse-style ale that hails from the Walloon region of Belgium, this yeast is one of the funkiest \"clean\" yeast we have in our stable. It imparts a slight earthy funk and tart character to the beer, and is a very mild producer of some slightly spicy and mildly smokey flavor compounds. This yeast exhibits absurdly high attenuation, resulting in a practically bone-dry beer. If desired, we recommend controlling the dryness by adjusting the mash temperature or adding malts or adjuncts to the mash tun that will lend some body and residual sweetness to the beer. Use this yeast for any farmhouse style or experimental Belgian ale.' WHERE `id` = 166;
        UPDATE yeasts SET `description`='This yeast was isolated from a beer crafted by a well-known producer of Belgian-style ales in the Northeastern United States. This yeast produces a very mild spiciness and earthy flavor and aroma which is complemented by a subtle but magnificent array of fruity esters, including pear and light citrus fruit. The brewery from which this strain was isolated uses it in a very versatile manner across an array of Belgian styles. We prefer using this yeast for any and all light Belgian beers, including Wit, Belgian Pale and Belgian Blond, in addition to any experimental fruit beers in which a more unique and robust flavor and aroma profile is desired. Expect this yeast to produce a large, thick krausen.' WHERE `id` = 167;
        UPDATE yeasts SET `description`='A blend of two unique yeast strains isolated from beers that embody the saison style, this blend is a balance of the many characteristic saison flavors and aromas. One yeast strain is a good attenuator that produces a spicy and mildly tart and tangy beer with a full mouthfeel. The other yeast strain is also a good attenuator that produces a delightful ester profile of grapefruit and orange zest and imparts a long, dry and earthy finish to the beer. Together, they produce a dry but balanced beer with a unique flavor and aroma profile.' WHERE `id` = 168;
        UPDATE yeasts SET `description`='Dry Belgian Ale is single strain of Saccharomyces cerevisiae isolated from a unique golden strong ale. The profile is a complex and balanced mix of apple, pear and light citrus fruit with some mild spicy and peppery notes. The apparent attenuation of this strain ranges anywhere from 85-100%, depending upon the mash profile and the grist composition. For a yeast that\'s as dry as it is, it creates beers with a surprising amount of balance even without the use of specialty grains or adjuncts. While we haven\'t completed our own tests in house, this yeast is used at the brewery from which it was isolated to make big beers that are in the neighborhood of 12-16% ABV and sufficiently dry. Use Dry Belgian Ale as a primary fermenter in any big Belgian beer, or to unstick that pesky stuck fermentation. To achieve high attenuation, we recommend fermenting with this strain at 70-71 ºF for the first 2-3 days, and then bumping up the temperature to 74-75 ºF for the remainder of fermentation.' WHERE `id` = 169;
        UPDATE yeasts SET `description`='Leaves a fruity profile with woody, oak esters reminiscent of malt whiskey. Well suited for 90/ shilling or heavier ales including old ales and barleywines due to the level of attenuation (77-80%). Suggested fermentation temperature: 60-68F' WHERE `id` = 170;
        UPDATE yeasts SET `description`='A combination of several saison yeast strains for both fruity and spicy characteristics accompanied with dryness (attenuation ~ 80%). Suggested fermentation temperature: 75-85F.' WHERE `id` = 171;
        UPDATE yeasts SET `description`='This yeast produces classic Belgian-style ales - robust, estery with a large note of clove and fruit. Rated highly in sensory tests described in \"Brew Like a Monk\" for complexity and low production of higher alcohols. Attenuation 74-76%, fermentation temperature 66-72F.' WHERE `id` = 172;
        UPDATE yeasts SET `description`='Sourced from a defunct east coast brewery, this pure strain was identified as their \"ale-pitching yeast\". Good for all styles of American and English ales with high flocculation and a compact sedimentation. Suggested fermentation temperature: 60-68F; attenuation ~76%.' WHERE `id` = 173;
        UPDATE yeasts SET `description`='Isolated from the Hainaut region in Belgium, this pure yeast will produce flavors reminiscent of witbiers. Suggested fermentation temperature: 70-76. Attenuation ~76%.' WHERE `id` = 174;
        UPDATE yeasts SET `description`='Sourced from the same east coast brewery as ECY10, this was identified as their \"beer-pitching yeast\" (i.e. lager yeast). The strain was identified as S. cerevisae, hence it is not a true lager yeast, but can ferment at lager fermentation temperatures. Clean and crisp when fermented at 58-68F; attenuation ~78%.' WHERE `id` = 175;
        UPDATE yeasts SET `description`='Traditional Belgian yeast with a complex, dry, fruity malt profile. Rated highly in sensory tests described in \"Brew Like a Monk\" for complexity and low production of higher alcohols. Attenuation 74-76%; fermentation temperature: 66-72F.' WHERE `id` = 176;
        UPDATE yeasts SET `description`='This strain leaves a smooth, full farmhouse character with mild esters reminiscent of apple pie spice. Attenuation 76-78%; fermentation temperature: 75-82F.' WHERE `id` = 177;
        UPDATE yeasts SET `description`='Produces a bold, citrusy character which accentuates mineral and hop flavors. Well suited for classic English pale ales and ESB.  Attenuation 73-75%; fermentation temperature: 64-69F.' WHERE `id` = 178;
        UPDATE yeasts SET `description`='This yeast has a complex woody ester and is typically under-attenuating (does not ferment malto-triose) leaving a pronounced malt profile with a slight sweetness that is perfect for milds and bitters. Apparent attenuation: 66-70%; fermentation temperature: 60-68F.' WHERE `id` = 179;
        UPDATE yeasts SET `description`='Produces a clean lager-like profile at ale fermentation temperatures. Smooth mineral and malt flavors come through with a clean, lightly yeasty flavor and aroma in the finish. Recommended fermentation temperature: 58-66F; attenuation:75-78%.' WHERE `id` = 180;
        UPDATE yeasts SET `description`='This yeast exhibits a clean, crisp lager in the traditional northern German character. Use in German pilsners including Kellerbier. Recommended fermentation temperature: 46-54F; attenuation: 74-76%.' WHERE `id` = 181;
        UPDATE yeasts SET `description`='A unique ale yeast with an abundance of citrusy esters accentuating American-style hops in any pale ale, IPA, double IPA. Low flocculation. Attenuation: 73-75%; suggested fermentation temperature: 65-70F.' WHERE `id` = 182;
        UPDATE yeasts SET `description`='Top fermenting strain for Belgian witbier and wheats.  Spicy and lightly phenolic.' WHERE `id` = 183;
        UPDATE yeasts SET `description`='A dry lager yeast with high attenuation.  Ferments clean and malty.' WHERE `id` = 184;
        UPDATE yeasts SET `description`='Top fermenting yeast that most suitable for amber coloured and dark beers. Fast fermentation with low residual sugar. Formation of fruity esters.' WHERE `id` = 185;
        UPDATE yeasts SET `description`='General purpose dry ale yeast with a very good reputation.  Produces significant fruity flavors.  No phenolics.  Clean, fruity finish.' WHERE `id` = 186;
        UPDATE yeasts SET `description`='BRY-97 produces some esters which results in beers that are slightly estery and almost neutral.' WHERE `id` = 187;
        UPDATE yeasts SET `description`='Belle Saison produces esters and phenols, which results in beers with fruity, peppery and spicy flavors and aromas.' WHERE `id` = 188;
        UPDATE yeasts SET `description`='Neutral flavor and aroma. Alcohol resistant. Not able to utilize maltotriose.' WHERE `id` = 189;
        UPDATE yeasts SET `description`='Typical German lager yeast. Crisp and clean finish.' WHERE `id` = 190;
        UPDATE yeasts SET `description`='German wheat beer yeast from Bavaria producing typical banana and clovy flavors.' WHERE `id` = 191;
        UPDATE yeasts SET `description`='Neutral flavors and aroma.' WHERE `id` = 192;
        UPDATE yeasts SET `description`='Windsor produces esters and the resulting beers display fruity flavors and aromas. This particular strain is not able to use the sugar maltotriose (a molecule com- posed of 3 glucose units) which is present in the wort in an average of 10-15% in all-malt worts. The consequence of this will be residual sweetness in the beer.' WHERE `id` = 193;
        UPDATE yeasts SET `description`='Mangrove Jack’s Cider Yeast is a high ester-producing strain, imparting wonderful flavor depth, revealing the full fruit potential of the juice. Ciders fermented using this strain are exceptionally crisp, flavorsome and refreshing in taste. This highly robust yeast has good fructose assimilation and is capable of fermenting under challenging conditions and over a wide temperature range. Mangrove Jack’s Cider Yeast is a highly flocculent strain, suitable for all styles of cider. Trace nutrients have been blended with the yeast in Mangrove Jack’s Cider Yeast sachets for optimum yeast health, fermentation performance and cider quality.' WHERE `id` = 194;
        UPDATE yeasts SET `description`='Newcastle Dark Ale Yeast successfully brings classic cask ale production into the homebrew or craft setting. This is a top-fermentation strain well suited for fermenting British ales, particularly dark and full bodied ales, mild brown ales and Scottish Heavy ales. Selected to not over attenuate, this strain will stop short of the low end gravities exhibited by other yeast strains. Dark fruity esters are pronounced when fermented at the appropriate temperature. Care should be taken to adjust hop bitterness to ensures it suits the ester character and complements the fuller bodied finish.' WHERE `id` = 195;
        UPDATE yeasts SET `description`='A neutral top-fermenting strain especially suited for brewing silky smooth light ales with a neutral yeast aroma and flavor contribution. This strain also works well for stronger ales where a soft and balanced mouth feel is desired and where the nutty, spicy and earthy hop and malt characteristics should be enhanced. This yeast strain is highly flocculent and not prone to autolysis, making it an excellent choice for both cask and bottle conditioned beer.' WHERE `id` = 196;
        UPDATE yeasts SET `description`='Workhorse Beer yeast is a true all rounder, suitable for a myriad of beer styles at extremely high gravities and different brewing temperatures. From Baltic porter to ambient temperature fermented lagers, this top-fermenting strain has such a clean flavor and aroma profile that it is suitable for almost every application. It is a robust strain with rapid and reliable fermentation performance, good attenuation properties, and ideally suited to making cask or bottle conditioned beers. This highly versatile strain also has very good ethanol tolerance up to 9% ABV and excellent temperature tolerance up to 90°F (32°C).' WHERE `id` = 197;
        UPDATE yeasts SET `description`='A classic top-fermenting yeast suited for brewing a range of German Weizens as well as Belgian Witbier. It has a very low flocculation rate and a clean, \"yeasty\" aroma which makes it ideal for beers that are traditionally served cloudy. This yeast creates beer with a low to completely dry level of sweetness, medium body with a silky mouth feel, and a delicious banana and spice aroma.' WHERE `id` = 198;
        UPDATE yeasts SET `description`='With a myriad of flavours and aromas embraced by master brewers all over Belgium, this strain has been specially developed to bring the best of these flavors to the home or craft brewer. Belgian ale yeast is an exceptional top-fermenting yeast strain creating distinctive beers with spicy, fruity and peppery notes. Ideal for fermentation of Belgian Saison or farmhouse style beers, but also suitable for other Belgian styles. This yeast is highly attenuative and has a high ethanol tolerance that makes it ideal for creating most Belgian beer styles, including Quadrupel styles of up to 14% ABV. At higher alcohol levels fermentation may take longer but the strain is robust enough to deal with almost anything. This strain successfully brings the sophistication of classic Belgian ale production to the home and small brewery.' WHERE `id` = 199;
        UPDATE yeasts SET `description`='U.S. West Coast Yeast is a high attenuating, top-fermenting strain that ferments with almost completely neutral attributes across a wide range of wort strengths and temperature ranges. It produces a moderately high acidity which allows the tangy citrus hop aromas to really punch through, while also enhancing toasted and dark malt characters. If you plan to use a lot of expensive flavourful hops as the prominent feature of your beer, use this yeast.' WHERE `id` = 200;
        UPDATE yeasts SET `description`='Famous the world over for its crisp, dry and uniquely malty and hoppy ales, this strain has been isolated and developed especially for the home and craft brewer from a commercial brewery in the heartland of British Brewing. Burton Union Yeast is a gentle but rapid fermenter that generates light and delicate ripe pear esters and does not strip away light malt character or body. Moderate acidity balances the silky smooth texture of beers fermented with this strain. When hops or malt aromas are stronger, the yeast contribution will be neutral. When used in lighter quality malt bases, the hops and esters are able to shine. Beers made with this yeast are quick to condition, giving you great beer in as little as 3 weeks.' WHERE `id` = 201;
        UPDATE yeasts SET `description`='Bohemian Lager is a classic bottom-fermenting, continental lager strain that produces elegant, well balanced beers. Bohemian Lager Yeast is characterized by its dry and clean palate, typical of traditional Czech brewing. This strain confers smooth, subtle yeast characteristics with muted fruit notes, resulting in refreshingly crisp lagers with expressive hop character. While rich and chewy, the beers fermented with this strain will not be sweet, but may have an elusive sweet malt flavor in the aftertaste. Lagering periods as short as 4 weeks may produce acceptable beer, but allowing beer to lager 6-8 weeks will result in beer that is richer, smoother, with a more refined aroma and flavor.' WHERE `id` = 202;
        UPDATE yeasts SET `description`='Strong sulfer component will reduce with aging.  Clean flavor, but with more ester production than regular German Ale Yeast.' WHERE `id` = 203;
        UPDATE yeasts SET `description`='From Suffolk county.  Products complex fruity and citrus flavors.  Slight sulfer production, but this will fade with ageing.' WHERE `id` = 204;
        UPDATE yeasts SET `description`='From Staffordshire England.  Mild, but complex estery flavor.  High attenuation - ferments strong and dry.  Suitable for high gravity beers.' WHERE `id` = 205;
        UPDATE yeasts SET `description`='Traditional English Ale style yeast.  Produces ester character, and allows hop flavor through.  Leaves a slightly sweet malt character in ales.' WHERE `id` = 206;
        UPDATE yeasts SET `description`='A great choice for any cask conditioned British Ale.  Produces nice malt profile with a hint of fruit. Finishes dry and slightly tart. ' WHERE `id` = 207;
        UPDATE yeasts SET `description`='The revival of interest in historic and classic English IPA styles calls for a specialized yeast – this blend highlights hop bitterness and aroma while still allowing full expression of authentic water profiles and pale malts. Low to moderate ester level can be manipulated through fermentation temperature and pitching rate. Palate finish is typically neutral to mildly fruity with some maltiness. Good flocculation characteristics make this an excellent candidate for cask conditioning.' WHERE `id` = 208;
        UPDATE yeasts SET `description`='This strain is ideally suited to the production of west-coast style American craft beers, especially pale, IPA, red, and specialties. Thorough attenuation, temp tolerance, and good flocculation make this an easy strain to work with. Flavor is balanced neutral with mild ester formation at warmer temps, allowing hops, character malts, and flavorings to show through.' WHERE `id` = 209;
        UPDATE yeasts SET `description`='A full-bodied strain, finishing very malty with a complex flavor profile. This strain’s characteristics are very desirable in English style brown ales and porters. It produces a dense, rocky head during fermentation, and can be a slow to start and to attenuate. This yeast may continue to produce CO2 for an extended period after packaging or collection.' WHERE `id` = 210;
        UPDATE yeasts SET `description`='A very versatile ale strain from Belgium. Excellent for Belgian stout and Belgian Specialty ales. Ferments to dryness and produces moderate levels of esters without significant phenolic or spicy characteristics.' WHERE `id` = 211;
        UPDATE yeasts SET `description`='A great yeast for malt predominate ales. Produces light fruit and ethanol aromas along with soft, nutty flavors. Exhibits a mild malt profile with a neutral finish. Bright beers are easily achieved without any filtration. It is similar to our 1968 London ESB Ale but slightly less flocculent.' WHERE `id` = 212;
        UPDATE yeasts SET `description`='This strain was originally sourced from a now defunct brewery on the banks of the river Thames outside of Oxford, England. Thames Valley II produces crisp, dry beers with a rich malt profile and moderate stone fruit esters. This attenuative strain is also highly flocculent resulting in bright beers not requiring filtration. A thorough diacetyl rest is recommended after fermentation is complete.' WHERE `id` = 213;
        UPDATE yeasts SET `description`='This strain is well-suited to delicate lager styles where balance is key. Neutral flavor with crisp finish allows refined, subtle malt flavors to come through. Production of diacetyl and sulfur during fermentation is typically low.' WHERE `id` = 214;
        UPDATE yeasts SET `description`='Clean, dry flavor profile often used in aggressively hopped pilsner. Mild aromatics, slight sulfur production, dry finish.' WHERE `id` = 215;
        UPDATE yeasts SET `description`='This versatile lager strain is an excellent choice for brewing your favorite low alcohol lawnmower beer. Fermentations at low temperatures will produce clean lagers that accentuate the malt character of the beer. At high temperatures this strain maintains much of the lager character, but will also yield a mild ester profile that compliments hop aromas and flavors.' WHERE `id` = 216;
        UPDATE yeasts SET `description`='Traditional culture of North American and Canadian lagers, light pilsners and adjunct beers. Mildly malty profile, medium ester profile, well balanced. Malty finish.' WHERE `id` = 217;
        UPDATE yeasts SET `description`='From a famous brewery in Munich, this strain is a low diacetyl and low sulfur aroma producer. An excellent choice for malt driven lagers.' WHERE `id` = 218;
        UPDATE yeasts SET `description`='Direct from the Austrian Alps, this strain will produce rich, full-bodied and malty beers with a complex flavor profile and a great mouth feel. Attenuates well while still leaving plenty of malt character and body. Beers fermented with this strain will benefit from a temperature rise for a diacetyl rest at the end of primary fermentation.' WHERE `id` = 219;
        UPDATE yeasts SET `description`='This authentic Kolsch strain from one of Germany’s leading brewing schools has a rich flavor profile which accentuates a soft malt finish. It has Low or no detectable diacetyl production and will also ferment well at colder temperatures for fast lager type beers.' WHERE `id` = 220;
        UPDATE yeasts SET `description`='This yeast will help create medium to full body lagers with moderate fruit and bready malt flavors. The balance is slightly toward malt sweetness and will benefit from additional hop bittering. A fantastic strain for producing classic Bohemian lagers.' WHERE `id` = 221;
        UPDATE yeasts SET `description`='This blend includes a German ale strain with low ester formation and a dry, crisp finish. The Lactobacillus included produces moderate levels of acidity. The unique Brettanomyces strain imparts a critical earthy characteristic that is indicative of a true Berliner Weisse. When this blend is used, expect a slow start to fermentation as the yeast and bacteria in the blend is balanced to allow proper acid production. It generally requires 3-6 months of aging to fully develop flavor characteristics. Use this blend with worts containing extremely low hopping rates.' WHERE `id` = 222;
        UPDATE yeasts SET `description`='Wyeast’s QC Manager and World’s Tallest Microbiologist Greg Doss developed De Bom to create authentic Old- and New-World sour ale profiles but in a fraction of the time required by previous, less manly cultures. For best results, we recommend the following: no O2/aeration at beginning of fermentation; periodic dosing with O2 during fermentation to stimulate ethyl acetate production; frequent sampling to monitor development and complexity. Under optimum conditions, beers can be ready for consumption in 1-2 months.' WHERE `id` = 223;
        UPDATE yeasts SET `description`='Because the people don’t want something new … they want something Oud. And Bruin. This new exclusive sour blend is built for dark, malt-accented sour styles – like 3763 Roselaere™ it will create sharp acidity, but unlike 3763 it will leave the malt character intact, creating a balanced and complex end product. Excellent base for blending fruit in secondary (especially cherries or raspberries) and makes for an interesting Saison.' WHERE `id` = 224;
        UPDATE yeasts SET `description`='Lambic culture of Saccharomyces Cerevisiar and a mixture of yeasts and bacterias.  Blend of organisms helps create lactic flavor of Belgian Lambics.' WHERE `id` = 225;
        UPDATE yeasts SET `description`='This vigorous top fermenting Belgian style strain produces a distinct spicy character along with mild esters. Phenolics developed during fermentation may dissipate with conditioning. 3538 is an excellent choice for a variety of Belgian beer styles including pales, dubbels, and brown ales.' WHERE `id` = 226;
        UPDATE yeasts SET `description`='From the East Flanders - Antwerpen region of Belgium, this unique top fermenting yeast produces complex, classic Belgian aromas and flavors that meld well with premium quality pale and crystal malts. Well rounded and smooth textures are exhibited with a full bodied malty profile and mouthfeel.' WHERE `id` = 227;
        UPDATE yeasts SET `description`='Low to moderate ester production with subtle spiciness. Malty and full on the palate with initial sweetness. Finishes dry and slightly tart. Ferments well with no sluggishness.' WHERE `id` = 228;
        UPDATE yeasts SET `description`='This strain produces complex esters balanced with earthy/spicy notes. Slightly tart and dry with a peppery finish. A perfect strain for farmhouse ales and saisons.' WHERE `id` = 229;
        UPDATE yeasts SET `description`='This well balanced strain from northern Belgium will produce moderate levels of both fruity esters and spicy phenols while finishing dry with a hint of malt. 3739-PC is a robust & versatile strain that performs nicely in a broad range of Belgian styles.' WHERE `id` = 230;
        UPDATE yeasts SET `description`='Our blend of lambic cultures produce beer with a complex, earthy profile and a distinctive pie cherry sourness. Aging up to 18 months is required for a full flavor profile and acidity to develop. Specific proportions of a Belgian style ale strain, a sherry strain, two Brettanomyces strains, a Lactobacillus culture, and a Pediococcus culture produce the desirable flavor components of these beers as they are brewed in West Flanders. Propagation of this culture is not recommended and will result in a change of the proportions of the individual components. This blend will produce a very dry beer due to the super-attenuative nature of the mixed cultures.' WHERE `id` = 231;
        UPDATE yeasts SET `description`='A unique blend of Belgian Saccharomyces and Brettanomyces for emulating Trappist style beer from the Florenville region in Belgium. Phenolics, mild fruitiness and complex spicy notes develop with increased fermentation temperatures. Subdued but classic Brett character.' WHERE `id` = 232;
        UPDATE yeasts SET `description`='Spicy, phenolic, and tart in the nose. Very tart and dry on the palate. Phenols and esters well balanced, with a very dry and complex finish. High acid producer.' WHERE `id` = 233;
        UPDATE yeasts SET `description`='This alcohol tolerant strain produces complex and well-balanced Belgian Abbey style ales. Banana and fruit esters are complemented nicely with mild levels of phenolics and hints of acidity. Ester levels may be elevated by increasing gravity and fermentation temperatures.' WHERE `id` = 234;
        UPDATE yeasts SET `description`='One of two strains for mead making. Leaves 2-3% residual sugar in most meads. Rich, fruity profile complements fruit mead fermentation. Use additional nutrients for mead making.' WHERE `id` = 235;
        UPDATE yeasts SET `description`='Lactic acid bacteria isolated from a Belgian brewery. This culture produces moderate levels of acidity and is commonly found in many types of beers including gueuze, lambics, sour brown ales and Berliner Weisse. It is always used in conjunction with S.cerevisiae and often with various wild yeast. Use in wort or beer below 10 IBU is recommended due to the culture’s sensitivity to hop compounds.' WHERE `id` = 236;
        UPDATE yeasts SET `description`='This strain of wild yeast was isolated from brewery cultures in the Brussels region of Belgium. It produces the classic “sweaty horse blanket” character of indigenous beers such as gueuze, lambics and sour browns and may form a pellicle in bottles or casks. The strain is generally used in conjunction with S. cerevisiae, as well as other wild yeast and lactic bacteria. At least 3-6 months aging is generally required for flavor to fully develop.' WHERE `id` = 237;
        UPDATE yeasts SET `description`='Unlike most lactic acid bacteria used in brewing, Lactobacillus brevis will tolerate higher levels of IBUs in wort. 5223 will produce alcohol along with lactic acid during fermentation. Excellent for remixing the profile in a Lambic-style or Flanders sour ale, or for kettle souring wort for a balanced Berliner Weisse.' WHERE `id` = 238;
        UPDATE yeasts SET `description`='Lactic acid bacteria isolated from a Belgian brewery. This culture produces moderate levels of acidity and is commonly found in many types of beers including gueuze, lambics, sour brown ales and Berliner Weisse. It is always used in conjunction with S.cer' WHERE `id` = 239;
        UPDATE yeasts SET `description`='This is a wild yeast strain isolated from Belgian lambic beers. It produces a pie cherry-like flavor and sourness along with distinct “Brett” character. A pellicle may form in bottles or casks. To produce the classic Belgian character, this strain works best in conjunction with other yeast and lactic bacteria. It generally requires 3-6 months of aging to fully develop flavor characteristics.' WHERE `id` = 240;
        UPDATE yeasts SET `description`='Lactic acid bacteria used in the production of Belgian style beers where additional acidity is desirable. Often found in gueuze and other Belgian style beer. Acid production will increase with storage time. It may also cause “ropiness” and produce low levels of diacetyl with extended storage time.' WHERE `id` = 241;
        UPDATE yeasts SET `description`='To bring you a bit of English brewing heritage we developed the “Old Ale” blend, including an attenuative ale strain and a Brettanomyces strain, which will ferment well in dark worts and produce beers with nice fruitiness. Complex estery characters will emerge with age. Pie cherry and sourness will evolve from the Brettanomyces along with distinct horsey characteristics.' WHERE `id` = 242;
        UPDATE yeasts SET `description`='Mauribrew Weiss produces large quantities of fermentation aromas (esters, higher alcohols) that contribute to the complexity of Germanstyle wheat beers. Mauribrew Weiss is also suitable for special beers made with macerated fruits, honey or any kind of sugar based additional ingredients.' WHERE `id` = 243;
        UPDATE yeasts SET `description`='Lager 497 is a bottom fermenting lager yeast that produces highly desirable flavour characteristics consistent with quality lager beer. While producing almost no yeast head during fermentation, it is a rapid fermenter with a low oxygen requirement, generally completing within 5 days. This strain has good settling properties, resulting in a green beer of good clarity.' WHERE `id` = 244;
        UPDATE yeasts SET `description`='This strain was selected based on its ability to produce English-style ales. It is a strong fermenting strain with rapid attenuation of fermentable sugars. Most noteworthy is this strains alcohol tolerance, producing commercial ales with up to 9.5% alcohol.' WHERE `id` = 245;
");
    }

    /**
     * Migrate Down.
     */
    public function down()
    {

    }
}
